#!/bin/bash

# Settings
DEFAULT_MOUNT_POINT='/media/autobackupsd'
BACKUP_FOLDER='/media/hm/MainStorage/Fotos'
LOG_FOLDER='/var/log/autobackupsd'
BACKUP_COMMAND='/usr/local/bin/arcpics'

# Cancel any pending shutdown
shutdown -c

led() {
  echo "ring,$1,$2,$3" |  tee /proc/acpi/nuc_led > /dev/null
}

error () {
  led "90" "blink_fast" "red"  
}

check_exit_code() {
  if [ "$?" != "0" ]
  then
     echo "Error $1"
     error
     exit $?
  fi
}
  
if [[ ! $- == *i* ]]
then
  [ -d "$LOG_FOLDER" ] || mkdir "$LOG_FOLDER"
  LOG_FILE="$LOG_FOLDER/$(date +%F-%T).log"
  echo "Using log file '$LOG_FILE'"
  exec >> $LOG_FILE
  exec 2>&1
fi

# Must be 1
if [ "$ID_DRIVE_FLASH_SD" != "1" ]
then
  echo "Device is not a SD Card: $DEVNAME ."
  exit 1 # Exit silently.
fi

# Must be a block device
if [ ! -b "$DEVNAME" ]
then
  echo "Device '$DEVICENAME' is not a block device"
  error
  exit 1
fi

# Must be partition
if [ "$DEVTYPE" != "partition" ]
then
  echo "Device is not a partition: $DEVTYPE."
  error
  exit 1
fi


MOUNT_POINT=$(lsblk -o MOUNTPOINT -nr "$DEVNAME" | xargs)

ALREADY_MOUNTED=true
if [ -z "$MOUNT_POINT" ]
then
  echo "$DEVNAME not yet mounted. Mounting..."
  # Create dir if not exists
  MOUNT_POINT="$DEFAULT_MOUNT_POINT"
  if [ ! -d "$MOUNT_POINT" ]
  then
    mkdir "$MOUNT_POINT"
  fi
  # Mount device
  mount "$DEVNAME" "$MOUNT_POINT"
  check_exit_code "Mounting $DEVNAME"
  ALREADY_MOUNTED=false
else 
  echo "$DEVNAME mounted in $MOUNT_POINT"
fi

if [ ! -d "$MOUNT_POINT/DCIM" ]
then
  echo "SD Card does not contains a picture folder: $MOUNT_POINT/DCIM"  
  exit 1
fi

echo "Starting backup from $MOUNT_POINT/DCIM"

led "70" "fade_medium" "green"

$BACKUP_COMMAND "$MOUNT_POINT/DCIM"
check_exit_code "Backup script"

led "70" "fade_fast" "green"

if [ "$ALREADY_MOUNTED" == false ] 
then
  echo "Unmounting $DEVNAME"
  umount "$DEVNAME"
fi

echo "Done!"
led "100" "none" "green"

