#!/bin/bash

[ "$TMPDIR" ] || TMPDIR=/tmp

# Settings
DEFAULT_MOUNT_POINT='/media/autobackupsd'
LOG_FOLDER='/var/log/autobackupsd'
HOME_LOG_FOLDER="$HOME/.autobackupsd"
BACKUP_COMMAND='/usr/local/bin/arcpics'
PIPE="$TMPDIR/autobackupsd.pipe"
NOTIFY=false


if [ -f /etc/autobackupsd ]
then
  echo "Reading config: /etc/autobackupsd"
  source /etc/autobackupsd
fi

led() {
  if [ -w /proc/acpi/nuc_led ]
  then
    echo "ring,$1,$2,$3" |  tee /proc/acpi/nuc_led > /dev/null
  fi
}

error () {
  if [ "$1" ]
  then
    printf "\033[91m$1\033[0m\n"
    notification "$1"
  fi
  led "90" "blink_fast" "red"  
}

check_exit_code() {
  EXIT_CODE=$?
  if [ "$EXIT_CODE" != "0" ]
  then     
     error "Error $1"
     [ "$2" == "noexit" ] && return $EXIT_CODE || exit $EXIT_CODE
  fi
}

info() {
  echo $1
  notification "$1"
}

notification() {
  
  [ $NOTIFY == false ] && return 0

  if [ -z "$TELEGRAM_BOT_KEY" ]
  then
      echo "No TELEGRAM_BOT_KEY"
      return 1
  fi

  if [ -z "$TELEGRAM_CHAT_ID" ]
  then
      echo "No TELEGRAM_CHAT_ID"
      return 1
  fi
  
  MESSAGE=$(printf "$1")  
  curl -m 5 "https://api.telegram.org/bot$TELEGRAM_BOT_KEY/sendMessage?parse_mode=Markdown&chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=*SD Backup:* $MESSAGE" > /dev/null 2>&1 &
}

create-log() {
  [ -d "$LOG_FOLDER" ] || mkdir "$LOG_FOLDER" 2> /dev/null
  if  [ ! -w "$LOG_FOLDER" ]
  then
    LOG_FOLDER="$HOME_LOG_FOLDER"
    [ -d "$LOG_FOLDER" ] || mkdir "$LOG_FOLDER"
  fi

  LOG_FILE="$LOG_FOLDER/$(date +%F-%T).log"
}

redirect-output() {
  if [ -w "$LOG_FOLDER" ]
    then    
      echo "Using log file '$LOG_FILE'"
      exec >> $LOG_FILE
      exec 2>&1
  fi
}

sdremoved() {
  echo 'SD Removed.'
  if [ -z "$(who)" ]
  then
     shutdown -P
  fi
  led "0" "fade_medium" "green"
}

backup-device() {
  
  if [ "$1" ]
  then
    DEVNAME="$1"
  fi

  if [ -z "$DEVNAME" ]
  then
    error "No backup device specified."
    return 1
  fi

  # Must be a block device
  if [ ! -b "$DEVNAME" ]
  then  
    error "Device '$DEVNAME' is not a block device"
    return 1
  fi

  MOUNT_POINT=$(lsblk -o MOUNTPOINT -nr "$DEVNAME" | xargs)

  ALREADY_MOUNTED=true
  if [ -z "$MOUNT_POINT" ]
  then
    echo "$DEVNAME not yet mounted. Mounting..."
    # Create dir if not exists
    MOUNT_POINT="$DEFAULT_MOUNT_POINT"
    if [ ! -d "$MOUNT_POINT" ]
    then
      mkdir "$MOUNT_POINT"
    fi
    # Mount device
    mount "$DEVNAME" "$MOUNT_POINT"
    check_exit_code "Mounting $DEVNAME" noexit
    [ "$?" != "0" ] && return $?
    
    ALREADY_MOUNTED=false
  else 
    echo "$DEVNAME mounted in $MOUNT_POINT"
  fi

  if [ ! -d "$MOUNT_POINT/DCIM" ]
  then
    echo "SD Card does not contains a picture folder: $MOUNT_POINT/DCIM"  
    return 1
  fi

  if [ -w "$LOG_FOLDER" ]
  then
    LOG_RESULTS_FILE=${LOG_FILE/.log/.result}
  fi

  info "Starting backup from $MOUNT_POINT/DCIM"

  led "70" "fade_medium" "green"

  $BACKUP_COMMAND -l "$LOG_RESULTS_FILE" "$MOUNT_POINT/DCIM"
  check_exit_code "Backup script" noexit
  [ "$?" != "0" ] && return $?

  led "70" "fade_fast" "green"

  if [ "$ALREADY_MOUNTED" == false ] 
  then
    echo "Unmounting $DEVNAME"
    umount "$DEVNAME"
  fi

  if [ -f "$LOG_RESULTS_FILE" ]
  then
    source "$LOG_RESULTS_FILE"
    notification "\n\n*Done!*\n\n $COPIED_NUMBER of $TOTAL_NUMBER ($DATA_AMOUNT) files copied to $DESTINATION_PATH in $DURATION_TIME.\n$FREE_SPACE_IN_DESTINATION_PATH available."
    echo "Done!"
  else
    info "Done!"
  fi
  led "100" "none" "green"

  return 0
}

write-pipe() {
  if [ ! -p $PIPE ]
  then
    "$PIPE not found"
    return 0
  fi

  echo "Writing $1 to $PIPE"
  echo "$1" > $PIPE
}

handle-udev() {
  
  if [ ! -p "$PIPE" ] 
  then 
    echo "$PIPE not found. Is daemon running?"
    exit 1
  fi

  # Must be a block device
  if [ ! -b "$DEVNAME" ]
  then    
    error "Device '$DEVNAME' is not a block device"
    exit 1
  fi

  # Must be 1
  if [ "$ID_DRIVE_FLASH_SD" != "1" ]
  then
    error "Device is not a SD Card: '$DEVNAME' ."
    exit 1 # Exit silently.
  fi

  # Must be partition
  if [ "$DEVTYPE" != "partition" ]
  then
    error "Device is not a partition: '$DEVTYPE'."
    exit 1
  fi
  
  line=$DEVNAME
  if [ "$1" ] 
  then
    line="$1"
  fi
  
  write-pipe "$line"
  
  # Cancel any pending shutdown
  shutdown -c > /dev/null 2>&1

  exit 0
}

start-read-bucle() {
  
  [ ! -p "$PIPE" ] && mkfifo "$PIPE"

  echo "Reading from FIFO: $PIPE"

  while true
  do      
      if read line <$PIPE; then          
          case "$line" in
            'stop')
              echo "Stopping..."
              break
              ;;
            'sdremoved')
              sdremoved
              ;;
            *)
              create-log
              #redirect-output
              backup-device $line
              ;;
          esac          
      fi
  done

  exit 0
}

# Entry point
create-log
case $1 in
  "--udev")        
    handle-udev $2
    ;;
  "--daemon")
    NOTIFY=true        
    start-read-bucle
    ;;
  "--stop-daemon")
    write-pipe "stop"
    ;;
  *)    
    backup-device $1
  ;;
esac
