#!/bin/bash

if [ ! -f ./autobackupsd ]
then
    echo "Wrong directory."
    exit
fi

INSTALL_DIR=/usr/local/bin

ln -s "$(readlink -f ../../main_archivepics.py)" "$INSTALL_DIR/arcpics"
ln -s "$(readlink -f ./autobackupsd)" "$INSTALL_DIR/autobackupsd"
ln -s "$(readlink -f ./sdremoved)" "$INSTALL_DIR/sdremoved"

if [ -d "/etc/udev/rules.d" ]
then
    cp ./99-autobackupsd.rules /etc/udev/rules.d/99-autobackupsd.rules
    udevadm control --reload
fi
