#!/bin/bash

INSTALL_DIR=/usr/local/bin

# **** Un-install ****
if [ "$1" == "uninstall" ]
then
    rm "$INSTALL_DIR/arcpics"
    rm "$INSTALL_DIR/autobackupsd"    
    rm "$INSTALL_DIR/sdremoved"
    rm "/etc/init/autobackupsd"
    
    if [ -f "/lib/systemd/system/autobackupsd.service" ]
    then    
        systemctl disable autobackupsd
        rm /lib/systemd/system/autobackupsd.service
    fi

    if [ -f "/etc/udev/rules.d/99-autobackupsd.rules" ]
    then
        rm "/etc/udev/rules.d/99-autobackupsd.rules"
        udevadm control --reload
    fi
    exit 0
fi


# **** Install ****
if [ ! -f ./autobackupsd ]
then
    echo "Wrong directory."
    exit
fi

ln -s "$(readlink -f ../../main_archivepics.py)" "$INSTALL_DIR/arcpics"
ln -s "$(readlink -f ./autobackupsd)" "$INSTALL_DIR/autobackupsd"

if [ -d "/lib/systemd/system" ]
then
    cp ./autobackupsd.service /lib/systemd/system
    systemctl enable autobackupsd
    systemctl start autobackupsd
fi

if [ -d "/etc/udev/rules.d" ]
then
    cp ./99-autobackupsd.rules /etc/udev/rules.d/99-autobackupsd.rules
    udevadm control --reload
fi
